baseURL = "https://navhub.org"
theme = "navhub-v2"

Paginate = 8

# English is the default language
#defaultContentLanguage = "en"
# Force to have /en/my-page and /fr/my-page routes, even for default language.
#defaultContentLanguageInSubdir = false

#[Languages]
#[Languages.en]
#title = "NavCoin Community Hub"
#weight = 1
#languageName = "English"


twitter_username = "navcoin"



[blackfriday]
  plainIDAnchors = true
  hrefTargetBlank = true

[taxonomies]
  category = "categories"
  guide_category = "guide_categories"
  filter = "filter"
  
# Main Menu
[[menu.main]]
    name = "Home"
    title = "Home"
    weight = 10
    identifier = "home"
    url = "/"
[[menu.main]]
    name = "News"
    title = "News"
    weight = 20
    identifier = "news"
    url = "/news/"
[[menu.main]]
    name = "Projects"
    title = "Projects"
    weight = 30
    identifier = "Project"
    url = "/projects/"
[[menu.main]]
    name = "Events"
    title = "Events"
    weight = 40
    identifier = "Events"
    url = "/events/"
[[menu.main]]
    name = "NavCoin Heroes"
    title = "NavCoin Heroes"
    weight = 50
    url = "/navcoin-heroes/"
    identifier = "navcoin-heroes"
[[menu.main]]
    name = "Community Assets"
    title = "Community Assets"
    weight = 60
    url = "/assets/"
    identifier = "assets"
[[menu.main]]
    name = "NavCollab"
    title = "NavCollab"
    weight = 90
    url = "https://collab.navcoin.org"
    identifier = "collab"
[[menu.main]]
    name = "NavCoin.org"
    title = "NavCoin.org"
    weight = 80
    url = "https://NavCoin.org"
    identifier = "navcoin"
